#!/bin/sh

# Set these paths appropriately

BIN=/home/lowx/Documents/Professionnel/Etude/Master_AIGLE/M1/Extraction_Connaissances_Données/TreeTagger/bin
CMD=/home/lowx/Documents/Professionnel/Etude/Master_AIGLE/M1/Extraction_Connaissances_Données/TreeTagger/cmd
LIB=/home/lowx/Documents/Professionnel/Etude/Master_AIGLE/M1/Extraction_Connaissances_Données/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
