#!/bin/sh

# Set these paths appropriately

BIN=/home/lowx/Documents/Professionnel/Etude/Master_AIGLE/M1/Extraction_Connaissances_Données/TreeTagger/bin
CMD=/home/lowx/Documents/Professionnel/Etude/Master_AIGLE/M1/Extraction_Connaissances_Données/TreeTagger/cmd
LIB=/home/lowx/Documents/Professionnel/Etude/Master_AIGLE/M1/Extraction_Connaissances_Données/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian-utf8.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
